services:
  db:
    image: mysql
    ports:
      - "3307:3306"   # ใช้ 3307 แทน 3306 บน host
    environment:
      MYSQL_ROOT_PASSWORD: password

  phpmyadmin:
    image: phpmyadmin
    ports:
      - "9000:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
